shamefullyHoist: true
shellEmulator: true

catalogs:
  dev:
    '@eslint/config-inspector': ^1.5.0
    '@types/node': ^25.6.0
    '@typescript/native-preview': 7.0.0-dev.20260107.1
    bumpp: ^11.0.1
    eslint-typegen: ^2.3.1
    jiti: ^2.6.1
    nano-staged: ^1.0.2
    oxfmt: ^0.44.0
    publint: ^0.3.18
    simple-git-hooks: ^2.13.1
    tsdown: ^0.21.7
    typescript: ^6.0.2
    unplugin-unused: ^0.5.7
  peer:
    '@unocss/eslint-plugin': ^66.6.8
    eslint: ^10.2.0
    eslint-plugin-better-tailwindcss: ^4.4.0
  prod:
    '@antfu/eslint-config': ^8.1.1
    defu: ^6.1.7
    eslint-flat-config-utils: ^3.1.0

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
